# Διαδρομή προς το το βασικό directory
ROOT = ../..

# Το όνομα του executable προγράμματος που θέλουμε να κάνουμε compile
PROGRAM = vector_example

# Λίστα από .o files που χρειάζεται το πρόγραμμα
#
# Εφόσον χρησιμοποιούμε το ADTVector, χρειαζόμαστε κάποια υλοποίησή του!
# Επιλέγουμε την υλοποίησή του μέσω Dynamic Array που υπάρχει στο modules/UsingDynamicArray/ADTVector.o
#
OBJS = main.o $(MODULES)/UsingDynamicArray/ADTVector.o

# Ο βασικός κορμός του Makefile
include $(ROOT)/common.make