# Λίστα με objects (.o) για κάθε εκτελέσιμο που θέλουμε να φτιάξουμε.
#
# Εφόσον χρησιμοποιούμε το ADTVector, χρειαζόμαστε κάποια υλοποίησή του!
# Επιλέγουμε την υλοποίησή του μέσω Dynamic Array που υπάρχει στο modules/UsingDynamicArray/ADTVector.o
#
vector_example_OBJS = main.o $(MODULES)/UsingDynamicArray/ADTVector.o

# Ο βασικός κορμός του Makefile
include ../../common.mk