# Λίστα με objects (.o) για κάθε εκτελέσιμο που θέλουμε να φτιάξουμε.
#
# Για το ADTVector χρησιμοποιούμε την υλοποίηση του k08.a library.
#
vector_example_OBJS = tests.o $(LIB)/k08.a

# Ο βασικός κορμός του Makefile
include ../../common.mk