# Λίστα με objects (.o) για κάθε εκτελέσιμο που θέλουμε να φτιάξουμε.
#
# Εφόσον χρησιμοποιούμε το ADTMap, χρειαζόμαστε κάποια υλοποίησή του!
# Επιλέγουμε την υλοποίηση μέσω ADTSet, οπότε χρειαζόμαστε και υλοποίηση του
# ATDSet, παίρνουμε αυτή μέσω BST που υπάρχει στο modules/UsingBinarySearchTree/ADTSet.o
#
map_example_OBJS = tests.o $(MODULES)/UsingADTSet/ADTMap.o $(MODULES)/UsingBinarySearchTree/ADTSet.o

# Ο βασικός κορμός του Makefile
include ../../common.mk