# Λίστα με objects (.o) για κάθε εκτελέσιμο που θέλουμε να φτιάξουμε.
#
# Για το ADTSet χρησιμοποιούμε την υλοποίηση μέσω AVL
#
set_example_OBJS = tests.o $(MODULES)/UsingAVL/ADTSet.o

# Ο βασικός κορμός του Makefile
include ../../common.mk
