# Λίστα με objects (.o) για κάθε εκτελέσιμο που θέλουμε να φτιάξουμε.
#
# Εφόσον χρησιμοποιούμε το ADTSet, χρειαζόμαστε κάποια υλοποίησή του!
# Επιλέγουμε την υλοποίησή του μέσω BST που υπάρχει στο modules/UsingBinarySearchTree/ADTSet.o
#
set_example_OBJS = tests.o $(MODULES)/UsingBinarySearchTree/ADTSet.o

# Ο βασικός κορμός του Makefile
include ../../common.mk