# Λίστα με objects (.o) για κάθε εκτελέσιμο που θέλουμε να φτιάξουμε.
#
# Χρειαζόμαστε την υλοποίηση του ADTIntVector, και το k08.a library για το ADTVector.
#
fibonacci_test_OBJS = fibonacci_test.o fibonacci.o ADTIntVector.o $(LIB)/k08.a

ADTIntVector_test_OBJS = ADTIntVector_test.o ADTIntVector.o $(LIB)/k08.a

# Ο βασικός κορμός του Makefile
include ../../common.mk