# Λίστα με objects (.o) για κάθε εκτελέσιμο που θέλουμε να φτιάξουμε.
#
# Χρειαζόμαστε την υλοποίηση του ADTIntVector και του ADTVector
#
fibonacci_test_OBJS = fibonacci_test.o fibonacci.o ADTIntVector.o $(MODULES)/UsingDynamicArray/ADTVector.o

ADTIntVector_test_OBJS = ADTIntVector_test.o ADTIntVector.o $(MODULES)/UsingDynamicArray/ADTVector.o

# Ο βασικός κορμός του Makefile
include ../../common.mk
