# Λίστα με objects (.o) για κάθε εκτελέσιμο που θέλουμε να φτιάξουμε.
#
# Χρειαζόμαστε την υλοποίηση του ADTIntVector, και το k08.a library για το ADTVector.
#
int_vector_example_OBJS = main.o ADTIntVector.o $(LIB)/k08.a

ADTIntVector_tests_OBJS = ADTIntVector_tests.o ADTIntVector.o $(LIB)/k08.a

# Ο βασικός κορμός του Makefile
include ../../common.mk