# Λίστα με objects που περιέχει το k08.a library
k08.a_OBJS =									\
	$(MODULES)/UsingDynamicArray/ADTVector.o	\
	$(MODULES)/UsingLinkedList/ADTList.o		\
	$(MODULES)/UsingAVL/ADTSet.o				\
	$(MODULES)/UsingADTList/ADTStack.o			\
	$(MODULES)/UsingADTList/ADTQueue.o			\
	$(MODULES)/UsingHeap/ADTPriorityQueue.o		\
	$(MODULES)/UsingADTSet/ADTMap.o

# Ο βασικός κορμός του Makefile
include ../common.mk
