# Οι κανόνες για τη δημιουργία του k08.a υπάρχουν στο common.mk (για να είναι διαθέσιμοι
# σε όλα τα Makefiles). Το Makefile αυτό χρησιμεύει απλά για να μπορούμε να δημιουργήσουμετο
# k08.a εκτελέντας "make" στο lib directory.

include ../common.mk

all: k08.a
k08.a: $(LIB)/k08.a