# Λίστα με τα executables που θέλουμε να κάνουμε compile
PROGS = unit_tests

# Λίστα από .o files που χρειάζεται κάθε πρόγραμμα (μια μεταβλητή ανά executable)
unit_tests_OBJS = unit_tests.o ADTVector.o

# Ο βασικός κορμός του Makefile
include ../../common.mk