# Διαδρομή προς το το βασικό directory
ROOT = ../..

# Το όνομα του executable προγράμματος που θέλουμε να κάνουμε compile
PROGRAM = unit_tests

# Λίστα από .o files που χρειάζεται το πρόγραμμα
OBJS = unit_tests.o ADTVector.o

# Ο βασικός κορμός του Makefile
include $(ROOT)/common.make