# Διαδρομή προς το το βασικό directory
ROOT = ../..

# Το όνομα του executable προγράμματος που θέλουμε να κάνουμε compile
PROGRAM = unit_tests

# Λίστα από .o files που χρειάζεται το πρόγραμμα
# Χρειαζόμαστε και μια υλοποίηση του ADTList, παίρνουμε αυτή μέσω LinkedList!
#
OBJS = unit_tests.o ADTStack.o ADTQueue.o $(MODULES)/UsingLinkedList/ADTList.o

# Ο βασικός κορμός του Makefile
include $(ROOT)/common.make