# Λίστα με objects (.o) για κάθε εκτελέσιμο που θέλουμε να φτιάξουμε.
#
# Χρειαζόμαστε υλοποιήσεις των ADTVector και ADTMap, αλλά και του ADTSet που χρησιμοποιείται από την υλοποίηση του ADTMap
#
pair_sum_test_OBJS = pair_sum_test.o pair_sum.o $(MODULES)/UsingDynamicArray/ADTVector.o $(MODULES)/UsingADTSet/ADTMap.o $(MODULES)/UsingAVL/ADTSet.o

# Ο βασικός κορμός του Makefile
include ../../common.mk
