# Λίστα με objects (.o) για κάθε εκτελέσιμο που θέλουμε να φτιάξουμε.
#
# Για το ADTMap χρησιμοποιούμε την υλοποίηση του k08.a library.
#
pair_sum.test_OBJS = pair_sum.test.o pair_sum.o $(LIB)/k08.a

# Ο βασικός κορμός του Makefile
include ../../common.mk