# Διαδρομή προς το το βασικό directory
ROOT = ../..

# Compiler options
# Το -I<dir> λέει στον compiler να ψάξει στο συγκεκριμένο directory για include files
#
CFLAGS = -g -Wall -I../../include

# Το όνομα του executable προγράμματος που θέλουμε να κάνουμε compile
PROGRAM = unit_tests

# Λίστα από .o files που χρειάζεται το πρόγραμμα
OBJS = unit_tests.o ADTList.o

# Ο βασικός κορμός του Makefile
include $(ROOT)/common.make